sudo: required
dist: trusty
language: node_js
node_js:
  - "node"

cache:
  yarn: true
  directories:
    - node_modules

before_install:
 - export CHROME_BIN=/usr/bin/google-chrome
 - export DISPLAY=:99.0
 - sh -e /etc/init.d/xvfb start
 - sudo apt-get update
 - sudo apt-get install -y libappindicator1 fonts-liberation
 - wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
 - sudo dpkg -i google-chrome*.deb

script: ./scripts/travis.sh
#- npm run eslint
#- npm run flow
#- npm run test

after_success:
- sh ./scripts/travis-push.sh

stages:
#  - lintAndTest
#  - releaseCanary
  - release
jobs:
  # stage: optional is allowed to be failure
  fast_finish: true
#  allow_failures:
#    - stage: testFuncOptional
  include:
    # https://docs.travis-ci.com/user/build-stages/deploy-github-releases/
    - stage: release
      if: (branch = master) AND (type = api)
      env: TRAVIS_MODE=release
      deploy:
        provider: releases
        api_key:
          secure: $GH_TOKEN
        file_glob: true
        file: dist/*
        draft: true
        skip_cleanup: true
        on:
          tags: true
    # publish canary package if on master
#    - stage: releaseCanary
#      if: branch = master AND type != pull_request
#      env: TRAVIS_MODE=releaseCanary
    # Required tests
    - stage: lintAndTest
      env:   TRAVIS_MODE=lint
    - stage: lintAndTest
      env:   TRAVIS_MODE=flow
    - stage: lintAndTest
      env:   TRAVIS_MODE=unitTests
