conditions: v1
sudo: required
dist: trusty
language: node_js
node_js:
  - "node"

addons:
  chrome: stable

cache:
  yarn: true
  directories:
    - node_modules

before_install:
 - export DISPLAY=:99.0
 - sh -e /etc/init.d/xvfb start
# - chmod +x ./scripts/travis-push.sh
 - chmod +x ./scripts/travis.sh

script: ./scripts/travis.sh
#- npm run eslint
#- npm run flow
#- npm run test

stages:
  - tests
    if: (branch = master) OR (tag IS present) OR (type = pull_request)
  - releaseCanary
  - release
  - deploy

jobs:
  # stage: optional is allowed to be failure
  fast_finish: true
#  allow_failures:
#    - stage: testFuncOptional
  include:
    # https://docs.travis-ci.com/user/build-stages/deploy-github-releases/
    - stage: release
      name: "Releasing a new version"
      if: tag IS present
      env: TRAVIS_MODE=release
      deploy:
        - provider: releases
          api_key:
            secure: $GH_TOKEN
          file_glob: true
          file: dist/*
          prerelease: true
          skip_cleanup: true
          on:
            branch: master
            tags: true
        - provider: npm
          api_key: $NPM_TOKEN
          email: $NPM_EMAIL
          skip_cleanup: true
          on:
            tags: true
            branch: master
    # publish canary package if on master
    - stage: releaseCanary
      if: (branch = master) AND (type != pull_request) AND commit_message !~ /^chore\(release\)/
      env: TRAVIS_MODE=releaseCanary
      deploy:
        provider: npm
        api_key: $NPM_TOKEN
        email: $NPM_EMAIL
        skip_cleanup: true
        tag: canary
        on:
          tags: false
          branch: master
    # Required tests
    - stage: tests
      name: "Running lint"
      env:   TRAVIS_MODE=lint
    - stage: tests
      name: "Running Flow type check"
      env:   TRAVIS_MODE=flow
    - stage: tests
      name: "Running unit tests"
      env:   TRAVIS_MODE=unitTests

